name: deploy

on: push
jobs:
  deploy:
    strategy:
      matrix:
        host: [proxy, endpoint]

    name: Deploy ${{ matrix.host }} host
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Configure cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy configuration
        run: nix run .#rebuild-server -- ${{ matrix.host }}
