name: deploy

on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Configure SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy configuration on sequoia
        run: .github/rebuild-server sequoia $(cat modules/by-name/constants/endpoint.txt)

      - name: Deploy configuration on pine
        run: .github/rebuild-server pine $(cat modules/by-name/constants/proxy.txt)

