name: deploy

on: push
jobs:
  deploy:
    strategy:
      matrix:
        host: [proxy, endpoint]

    name: Deploy ${{ matrix.host }} host
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Configure SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install `nixos-rebuild`
        run: nix-env -iA nixos-rebuild -f '<nixpkgs>'

      - name: Deploy configuration
        run: .github/rebuild-server ${{ matrix.host }} $(cat modules/by-name/constants/${{ matrix.host }}.txt)
